homepage:
    path:      /
    defaults:  { _controller: AppBundle:Default:index }

#api_login_check:
#    path: /api/login_check

authentication:
    path: /api/authentication
    defaults:  { _controller: AppBundle:Authentication:authentication }


secure_resource:
    path:      /api/secure-resource
    defaults:  { _controller: AppBundle:Default:secureResource }