homepage:
    path:      /
    defaults:  { _controller: AppBundle:Default:index }

authentication:
    path: /api/authentication
    defaults:  { _controller: AppBundle:Authentication:authentication }

proxy_files:
    path:      /proxy
    defaults:  { _controller: AppBundle:File:proxy }
    methods:  [GET]

get_user_files:
    path:      /api/user-files
    defaults:  { _controller: AppBundle:File:getUserFiles }
    methods:  [GET]

get_user_profile:
    path:      /api/user-profile
    defaults:  { _controller: AppBundle:User:getProfile }
    methods:  [GET]

get_user_calendars:
    path:     /api/calendar-list
    defaults: { _controller: AppBundle:Calendar:getCalendarList }
    methods:  [GET]

get_user_calendar_events:
    path:     /api/calendar-event-list/{ids}
    defaults: { _controller: AppBundle:Calendar:getCalendarEventList, ids: null }
    methods:  [GET]

bind_jira_account:
    path:      /api/bind-jira-account
    defaults:  { _controller: AppBundle:Jira:bindJiraAccount }
    methods:  [POST]

unbind_jira_account:
    path:      /api/unbind-jira-account
    defaults:  { _controller: AppBundle:Jira:unbindJiraAccount }
    methods:  [DELETE]