homepage:
    path:      /
    defaults:  { _controller: AppBundle:Default:index }

proxy_files:
    path:      /proxy
    defaults:  { _controller: AppBundle:File:proxy }
    methods:  [GET]

authentication:
    path: /api/authentication
    defaults:  { _controller: AppBundle:Authentication:authentication }

get_user_files:
    path:      /api/user-files
    defaults:  { _controller: AppBundle:File:getUserFiles }
    methods:  [GET]

get_user_profile:
    path:      /api/user-profile
    defaults:  { _controller: AppBundle:User:getProfile }
    methods:  [GET]

secure_resource:
    path:      /api/secure-resource
    defaults:  { _controller: AppBundle:User:secureResource }

calendar:
    path:     /api/calendar
    defaults: { _controller: AppBundle:Calendar:calendar }
    methods:  [POST, GET]

bind_jira_account:
    path:      /api/bind-jira-account
    defaults:  { _controller: AppBundle:Jira:bindJiraAccount }
    methods:  [POST]

unbind_jira_account:
    path:      /api/unbind-jira-account
    defaults:  { _controller: AppBundle:Jira:unbindJiraAccount }
    methods:  [DELETE]