homepage:
    path:      /
    defaults:  { _controller: AppBundle:Default:index }

authentication:
    path: /api/authentication
    defaults:  { _controller: AppBundle:Authentication:authentication }

secure_resource:
    path:      /api/secure-resource
    defaults:  { _controller: AppBundle:User:secureResource }

calendar:
    path:     /calendar
    defaults: { _controller: AppBundle:Calendar:calendar }
    methods:  [POST]

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /ainstainer/doc
