homepage:
    path:      /
    defaults:  { _controller: AppBundle:Default:index }

proxy_files:
    path:      /proxy
    defaults:  { _controller: AppBundle:File:proxy }
    methods:  [GET]

authentication:
    path: /api/authentication
    defaults:  { _controller: AppBundle:Authentication:authentication }


get_user_files:
    path:      /api/user-files
    defaults:  { _controller: AppBundle:File:getUserFiles }
    methods:  [GET]

secure_resource:
    path:      /api/secure-resource
    defaults:  { _controller: AppBundle:User:secureResource }

calendar:
    path:     /calendar
    defaults: { _controller: AppBundle:Calendar:calendar }
    methods:  [POST]
    methods:  [POST, GET]

