homepage:
    path:      /
    defaults:  { _controller: AppBundle:Default:index }

category:
    path: /category
    defaults: { _controller: AppBundle:Category:index }

category_get:
    path: /category/get
    defaults: { _controller: AppBundle:Category:get }

authentication:
    path: /api/authentication
    defaults:  { _controller: AppBundle:Authentication:authentication }

secure_resource:
    path:      /api/secure-resource
    defaults:  { _controller: AppBundle:User:secureResource }
    methods:  [POST]

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /ainstainer/doc