# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
    providers:
        database_users:
            entity:
                class: AppBundle:User


    firewalls:
        # Custom authentication firewall for all request thats starts from /api
        api:
            pattern: ^/api/(?!token)
            guard:
                authenticators:
                    - app.jwt_token_authenticator

        # Here you handle regular form authentication
#        main:
#            anonymous: ~
#            guard:
#                authenticators:
#                    - app.form_login_authenticator

    access_control:
        - { path: /api/token-authentication, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: [ROLE_ADMIN, ROLE_USER, ROLE_API_USER] }
#        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(css|js), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(_wdt|_profiler), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }