# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
    providers:
        database_users:
            entity:
                class: AppBundle:User
    firewalls:
        # Custom authentication firewall for all request thats starts from /api
         login:
              pattern:  ^/api/authentication
              stateless: false
              anonymous: true
         api:
              pattern: ^/api
              stateless: false
              guard:
                  authenticators:
                      - app.jwt_token_authenticator

        # Here you handle regular form authentication
#        main:
#            anonymous: ~
#            guard:
#                authenticators:
#                    - app.form_login_authenticator

    access_control:
        - { path: ^/api/authentication, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: [IS_AUTHENTICATED_FULLY ] }
        - { path: ^/(css|js), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(_wdt|_profiler), roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/, roles: ROLE_USER }