# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
  app.jwt_token_authenticator:
    class: AppBundle\Security\JwtAuthenticator
    arguments: ['@doctrine.orm.entity_manager', '@lexik_jwt_authentication.encoder','%kernel.debug%']

  app.google_user.auth:
    class: AppBundle\Services\GoogleUserAuthenticator
    arguments: ['@service_container']

  app.google_user.mail:
      class: AppBundle\Services\GoogleUserMail
      arguments: ['@service_container']