crud_index:
    path:     /
    defaults: { _controller: "RestApiTestBundle:Crud:index" }
    methods:  GET

crud_show:
    path:     /{id}/show
    defaults: { _controller: "RestApiTestBundle:Crud:show" }
    methods:  GET

crud_new:
    path:     /new
    defaults: { _controller: "RestApiTestBundle:Crud:new" }
    methods:  POST

crud_edit:
    path:     /{id}/edit
    defaults: { _controller: "RestApiTestBundle:Crud:edit" }
    methods:  [GET, POST, PUT]

crud_delete:
    path:     /{id}/delete
    defaults: { _controller: "RestApiTestBundle:Crud:delete" }
    methods:  DELETE

crud_upload:
    path: /upload
    defaults: { _controller: "RestApiTestBundle:Crud:upload" }
    methods: POST

crud_list:
    path: /list
    defaults: { _controller: "RestApiTestBundle:Crud:list" }
    methods: [GET, POST]

crud_list_links:
    path: /links
    defaults: { _controller: "RestApiTestBundle:Crud:links" }
    methods: [GET, POST]