rest_api_test_crud:
    resource: "@RestApiTestBundle/Resources/config/routing/crud.yml"
    prefix:   /crud

rest_api_test_homepage:
    path:     /
    defaults: { _controller: RestApiTestBundle:Default:index }

rest_api_test_user:
    path: /user/
    defaults: { _controller: RestApiTestBundle:User:index }

rest_api_test_user_id:
    path: /user/id/
    defaults: { _controller: RestApiTestBundle:User:id }

rest_api_test_user_post:
    path: /user/post/
    defaults: { _controller: RestApiTestBundle:User:post }

rest_api_test_google:
    path: /google
    defaults: { _controller: RestApiTestBundle:Default:google }

rest_api_test_upload:
    path: /upload
    defaults: { _controller: RestApiTestBundle:Default:upload }

rest_api_test_delete:
    path: /delete
    defaults: { _controller: RestApiTestBundle:Default:delete }

rest_api_test_getpermissions:
    path: /getpermissions
    defaults: { _controller: RestApiTestBundle:Default:getpermissions }

rest_api_test_deletepermission:
    path: /deletepermission
    defaults: { _controller: RestApiTestBundle:Default:deletepermission }

rest_api_test_anyonepermission:
    path: /anyone
    defaults: { _controller: RestApiTestBundle:Default:anyonepermission }

rest_api_test_domainpermission:
    path: /domain
    defaults: { _controller: RestApiTestBundle:Default:domainpermission }