services:
#    rest_api_test.example:
#        class: RestApi\TestBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    rest_api_test.file:
        class: RestApi\TestBundle\Services\FileService
        arguments: ["%app_key%", "%app_secret%", "%access_token%", "%box%"]
